version: '3'

services:
<<<<<<< HEAD
 app:
  build:
   context: .
   dockerfile: Dockerfile
  ports:
   - "9000:9000"
  volumes:
   - .models;/app/models
   - ./data:/app/data
   - ./predictions:/app/predictions
  environment:
   - MLFLOW_TRACKING_URI=http://mlflow:5000
  depends_on:
   - mlflow
  networks:
   - flowers-network


 mlflow:
  build:
   context: .
   dockerfile: Dockerfile.mlflow
  ports:
    - "5000:5000"
  volumes:
   - mlflow-data:/mlflow
  networks:
  - flowers-network

networks:
 flowers-network:
  driver: bridge


volumes:
 mlflow-data:
  driver: local
=======
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./models:/app/models
      - ./data:/app/data
      - ./predictions:/app/predictions
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    depends_on:
      - mlflow
    networks:
      - flowers-network

  mlflow:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    ports:
      - "5000:5000"
    volumes:
      - mlflow-data:/mlflow
    networks:
      - flowers-network

networks:
  flowers-network:
    driver: bridge

volumes:
  mlflow-data:
    driver: local
>>>>>>> refs/remotes/origin/main
